### PR TITLE
Windows Compatibility

### PR DESCRIPTION
**Pull request by paul70131**
Fixes compilation errors on Windows 10

### CODE REVIEW

**Comment by dbousque** [comment]
Hi @paul70131 . Thank you for your PR! I adapted it a bit in the `chore/windows_compatibility` branch on the main repo. Can you pull this branch and check if it works locally for you? You can run the python tests to try it out for example:
```shell
cd python && pip install -r dev-requirements.txt && ./local_build.sh && cd test && pip install -r requirements.txt && pytest -vv -s
```

**Comment by paul70131** [comment]
Hi,
Yes, the `chore/windows_compatibility` branch compiles and passes all tests locally.

The `local_build.sh` and `cython_build.sh` however do not work on Windows, are those files for development only?

**Comment by dbousque** [comment]
Ok nice thank you. Those are bash/sh scripts, they might not work on Windows depending on your shell. `batch_jaro_winkler` version `0.1.3` has been published with your changes. Can you try installing this new version and let me know of the result?

**Comment by dbousque** [comment]
Nice! Thank you for the contribution.

**Pull request merged**
